/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * READ-ONLY LLM CONTEXT - Do not edit this file.
 *
 * JSON File: agentcore/agentcore.json
 * Purpose: Top-level project configuration and agent environment details
 */

// ─────────────────────────────────────────────────────────────────────────────
// ROOT SCHEMA: AgentCoreProjectSpec
// ─────────────────────────────────────────────────────────────────────────────

interface AgentCoreProjectSpec {
  name: string; // @regex ^[A-Za-z][A-Za-z0-9]{0,35}$ @max 36 - CloudFormation stack name prefix
  version: string;
  description: string;
  agents: AgentEnvSpec[]; // Unique by name
  mcp?: AgentCoreMcpSpec; // Optional - see mcp.ts for full definition
}

// MCP spec placeholder (see mcp.ts)
interface AgentCoreMcpSpec {
  agentCoreGateways: unknown[];
  mcpRuntimeTools?: unknown[];
}

// ─────────────────────────────────────────────────────────────────────────────
// AGENT SCHEMA: AgentEnvSpec
// ─────────────────────────────────────────────────────────────────────────────

interface AgentEnvSpec {
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64 - unique within project
  id: string; // @min 1
  sdkFramework: SDKFramework;
  targetLanguage: TargetLanguage;
  modelProvider: ModelProvider;
  runtime: Runtime;
  mcpProviders: MCPProvider[];
  memoryProviders: MemoryProvider[];
  identityProviders: IdentityProvider[];
  remoteTools: RemoteTool[];
}

// ─────────────────────────────────────────────────────────────────────────────
// ENUMS
// ─────────────────────────────────────────────────────────────────────────────

type SDKFramework = 'Strands' | 'LangChain_LangGraph' | 'AutoGen' | 'CrewAI' | 'GoogleADK' | 'OpenAIAgents';
type TargetLanguage = 'Python' | 'TypeScript' | 'Other';
type ModelProvider = 'Bedrock' | 'Gemini' | 'OpenAI' | 'Anthropic';
type PythonRuntime = 'PYTHON_3_10' | 'PYTHON_3_11' | 'PYTHON_3_12' | 'PYTHON_3_13';
type NetworkMode = 'PUBLIC' | 'PRIVATE';
type ContainerBuildMode = 'LOCAL' | 'REMOTE' | 'NO_OP_REFERENCE';
type MemoryStrategyType = 'SEMANTIC' | 'SUMMARIZATION' | 'USER_PREFERENCE' | 'CUSTOM';

// Provider type literals follow [System][Component] naming convention
type ProviderType = 'AgentCoreMemory' | 'AgentCoreGateway' | 'AgentCoreIdentity' | 'AgentCoreCodeBrowser';

// Provider relation determines ownership vs reference
type Relation = 'own' | 'use';
type Access = 'read' | 'readwrite';

// Identity credential variant (forward-compatible for future credential types)
type IdentityCredentialVariant = 'ApiKeyCredentialProvider';

// ─────────────────────────────────────────────────────────────────────────────
// RUNTIME (discriminated union on 'artifact')
// ─────────────────────────────────────────────────────────────────────────────

type Runtime = CodeZipRuntime | ContainerImageRuntime | ReferencedEcrImageRuntime;

interface CodeZipRuntime {
  artifact: 'CodeZip';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9_]{0,47}$ @max 48
  pythonVersion: PythonRuntime;
  entrypoint: string; // @regex ^[a-zA-Z0-9_][a-zA-Z0-9_/.-]*\.py(:[a-zA-Z_][a-zA-Z0-9_]*)?$ e.g. "main.py:agent"
  codeLocation: string; // Directory path
  instrumentation?: Instrumentation; // OpenTelemetry settings, defaults to enabled
  networkMode?: NetworkMode; // default 'PUBLIC'
  description?: string;
}

interface Instrumentation {
  enableOtel: boolean; // default true - wrap entrypoint with opentelemetry-instrument
}

interface ContainerImageRuntime {
  artifact: 'ContainerImage';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9_]{0,47}$ @max 48
  buildMode: ContainerBuildMode;
  buildContextPath: string; // Directory path
  dockerfilePath: string; // @min 1
  imageUri?: string; // Required for REMOTE build
  networkMode?: NetworkMode; // default 'PUBLIC'
  description?: string;
}

/**
 * Runtime that references an external ECR image.
 * The actual image URI is defined in aws-targets.json referencedResources.ecrImages,
 * allowing different images for different deployment targets (dev vs prod).
 */
interface ReferencedEcrImageRuntime {
  artifact: 'ReferencedEcrImage';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9_]{0,47}$ @max 48
  imageRef: string; // @regex ^[a-zA-Z][a-zA-Z0-9_-]*$ @max 64 - key in aws-targets.json referencedResources.ecrImages
  networkMode?: NetworkMode; // default 'PUBLIC'
  description?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// PROVIDERS
// ─────────────────────────────────────────────────────────────────────────────

// Common provider fields
// name: @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64

interface MCPProvider {
  type: 'AgentCoreGateway';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  gatewayName: string; // @regex ^([0-9a-zA-Z][-]?){1,100}$ @max 100
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for gateway URL
}

// Memory Provider - discriminated union on 'relation'
type MemoryProvider = OwnedMemoryProvider | ReferencedMemoryProvider;

// Owner creates and manages the memory resource
interface OwnedMemoryProvider {
  type: 'AgentCoreMemory';
  relation: 'own';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  config: AgentCoreMemoryConfig;
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for memory ID
}

// Consumer references an existing memory by name
interface ReferencedMemoryProvider {
  type: 'AgentCoreMemory';
  relation: 'use';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  access?: Access; // default 'readwrite'
  namespaces?: string[]; // @min 1 if provided
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for memory ID
}

// Identity Provider - discriminated union on 'relation'
type IdentityProvider = OwnedIdentityProvider | ReferencedIdentityProvider;

// Owner creates and manages the identity credential provider
interface OwnedIdentityProvider {
  type: 'AgentCoreIdentity';
  variant: IdentityCredentialVariant;
  relation: 'own';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - e.g., AGENTCORE_IDENTITY_OPENAI
}

// Consumer references an existing identity provider by name
interface ReferencedIdentityProvider {
  type: 'AgentCoreIdentity';
  variant: IdentityCredentialVariant;
  relation: 'use';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - e.g., AGENTCORE_IDENTITY_OPENAI
}

// Remote Tool - discriminated union on 'type'
type RemoteTool = AgentCoreCodeBrowserTool | AgentCoreAgentInvocation | AgentCoreMcpRuntimeRef;

interface AgentCoreCodeBrowserTool {
  type: 'AgentCoreCodeBrowser';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  config?: Record<string, unknown>;
}

/**
 * Reference to a peer agent for agent-to-agent invocation.
 * Adding this grants the agent InvokeAgentRuntime permission and
 * sets an environment variable with the target agent's runtime ARN.
 */
interface AgentCoreAgentInvocation {
  type: 'AgentCoreAgentInvocation';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  targetAgentName: string; // @min 1 - name of the target agent from spec.agents array
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for target runtime ARN
}

/**
 * Reference to an MCP Runtime tool defined in mcp.json.
 * Adding this grants the agent InvokeAgentRuntime permission and
 * sets an environment variable with the runtime endpoint URL.
 */
interface AgentCoreMcpRuntimeRef {
  type: 'AgentCoreMcpRuntime';
  name: string; // @regex ^[a-zA-Z][a-zA-Z0-9]{0,63}$ @max 64
  description: string;
  mcpRuntimeName: string; // @min 1 - name of the MCP runtime from mcp.json mcpRuntimeTools
  envVarName: string; // @regex ^[A-Za-z_][A-Za-z0-9_]*$ @max 255 - env var for runtime endpoint URL
}

// ─────────────────────────────────────────────────────────────────────────────
// MEMORY CONFIGURATION
// ─────────────────────────────────────────────────────────────────────────────

interface AgentCoreMemoryConfig {
  eventExpiryDuration: number; // @min 7 @max 365 (days)
  memoryStrategies: MemoryStrategy[]; // @min 1
  description?: string;
}

interface MemoryStrategy {
  type: MemoryStrategyType;
  name?: string; // @regex ^[a-zA-Z][a-zA-Z0-9_]{0,47}$ @max 48
  description?: string;
  namespaces?: string[]; // @min 1 if provided
}
